### ISSUE TITLE
Fix Organization.extension.qualification

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#101]
Organization.extension.qualification is malformed and needs to be corrected.  It should match the FHIR R5 Organization.qualification resource.  See notes on #5 and #11. 
- [ ] extension should not be nested under qualification
- [ ] - cardinality should be 0..*
- [ ] - each of the underlying elements should NOT be extension, but their respective data types.

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/0176420c-1e12-4f5b-b87d-d19ae43ad9a8)

**Comment by enjoysparkling** [comment]
Match the same fields and definitions as the [FHIR Core R5 Organization.qualification](https://hl7.org/fhir/R5/organization-definitions.html#Organization.qualification).

**Comment by arunsundar-m** [comment]
@enjoysparkling @Gokulsignal It looks like if a single element is added, we will have them as an element under extension with url and value[x]

https://simplifier.net/packages/hl7.fhir.us.core/6.0.0/files/2024356

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/124249650/c355da42-1eb4-4baf-a065-e17b3f2342ac)

If there are multiple elements to be added under extension, then each of the element needs to be added as an extension.

https://simplifier.net/packages/hl7.fhir.us.core/6.0.0/files/2024356

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/124249650/58948a3b-24dd-48e8-b909-4dea476a160b)

I am exploring options, will discuss in today's catchup

**Comment by arunsundar-m** [comment]
@enjoysparkling Matt, I read through various examples, looks like if there are multiple elements inside an extension, those elements also appear as extensions. Can we mark this task as closed?

**Comment by enjoysparkling** [comment]
Try creating it from scratch in Forge, matching everything in [FHIR Core R5 Organization.qualification](https://hl7.org/fhir/R5/organization-definitions.html#Organization.qualification).
