### ISSUE TITLE
Delete the local ValueSet-us-core-procedure-code

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#114]
This needs to be changed to the https://hl7.org/fhir/us/core/ValueSet-us-core-procedure-code.html  (essentially, we should DELETE our extension/expansion version of this and use the US Core -provided one).  For Referrals, we should accept all of these procedure codes, not just the BHA list.

https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/6f8cb9ba59c7fcd02ed37713d7e17ea1d18cd440/input/vocabulary/valueset-us-core-procedure-code.json#L49C28-L49C28

**Comment by arunsundar-m** [comment]
@enjoysparkling ok, we can delete the valueset, what about the expansion for the the valuesets in the below code system?

This value set includes codes based on the following rules:

Include all codes defined in [http://www.ama-assn.org/go/cpt](http://terminology.hl7.org/5.0.0/CodeSystem-CPT.html)
Include codes from [http://snomed.info/sct](http://www.snomed.org/) where concept is-a 71388002 (Procedure)
Include all codes defined in [https://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets](http://terminology.hl7.org/5.0.0/CodeSystem-hcpcs-Level-II.html)
Include all codes defined in [http://www.cms.gov/Medicare/Coding/ICD10](http://terminology.hl7.org/5.0.0/CodeSystem-icd10PCS.html)
Include all codes defined in [http://www.ada.org/cdt](http://terminology.hl7.org/5.0.0/CodeSystem-CDT.html)
Include all codes defined in http://loinc.org/
