### ISSUE TITLE
Standardize metadata across profiles

### ISSUE THREAD

**Issue by arunsundar-m** [enjoysparkling/signal-mso-fhir-profiles#115]
The following changes have to be made to the profiles to have a uniform naming convention.
- Change the .url element to be https://signalbhn.org/fhir/StructureDefinition/episodeofcare 
-  Change .id element to be signal-episodeofcare
-  Change .name element to be signal-episodeofcare-profile
-  Add the .title element to be EpisodeOfCare Profile
- filename should be input\resources\StructureDefinition-profile-SignalEpisodeOfCare.json

List of profiles to be verified
- [x] StructureDefinition-profile-location
- [x] StructureDefinition-profile-OrganizationAffiliation
- [x] StructureDefinition-profile-patient
- [x] StructureDefinition-profile-practitioner
- [x] StructureDefinition-profile-PractitionerRole
- [x] StructureDefinition-profile-SignalHealthcareService
- [x] StructureDefinition-profile-SignalUSCoreEncounter
- [x] StructureDefinition-profile-SignalUSCoreOrganizationProfile

**Comment by enjoysparkling** [comment]
I think we landed on this format:

As per [Issue #93](https://github.com/enjoysparkling/signal-mso-fhir-profiles/issues/93), I would like to see some standardized metadata across our profiles.  This is an example done for EpisodeOfCare--follow this pattern:

-  Change the `.url` element to be `https://signalbhn.org/fhir/StructureDefinition/episodeofcare` 
-  Change `.id` element to be `signal-episodeofcare`
-  Change `.name` element to be `SignalEpisodeOfCare`
-  Add the `.title` element to be `EpisodeOfCare Profile`
- filename should be `input\resources\StructureDefinition-profile-SignalEpisodeOfCare.json`

This will allow it to be common across all profiles and make it display properly in Simplifier and our Capability Statement.
