### ISSUE TITLE
Create custom valuesets required for drop downs in UI

### ISSUE THREAD

**Issue by arunsundar-m** [enjoysparkling/signal-mso-fhir-profiles#117]
@enjoysparkling @Gokulsignal There are some additional value sets required to be created for drop downs in UI, which were pushed manually during deployment in QA.

Gokul - Please fill in the valueset details here.

**Comment by enjoysparkling** [comment]
Any progress on this?  What is missing?

**Comment by enjoysparkling** [comment]
Closed PR:  I really need some descriptions on where these came from. I am unable to review these without any supporting information.  E.g.
* Where did this list of codes come from for Region?
* We lost the hierarchy for the different service organizations - are both SOs using the same regions?? 
* etc.
