### ISSUE TITLE
ValueSet bugfix for Patient

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#12]
As a business user, I want to be able to be able to access all my value sets (seed tables) from my FHIR server.
- Azure FHIR service [does not have terminology services](https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/fhir-faq#does-azure-api-for-fhir-support-any-terminology-operations--) (see https://github.com/microsoft/fhir-server/issues/897, https://github.com/microsoft/fhir-server/issues/810), so we will need to host all [ValueSets as extensional](http://hl7.org/fhir/valueset.html#int-ext) files.
- We prefer developers utilize the canonical URL for [identifying a ValueSet](http://hl7.org/fhir/valueset.html#ident). So, any value set that does not have extended values from FHIR will need to be hosted from our package.  _Note:_ We should be able to keep the same canonical URL, as long as our package loads last, thereby loading and overriding the original package ValueSet with our expanded version.
- A [ValueSet expansion](https://www.hl7.org/fhir/valueset.html#expansion) shall keep the originally defined `.compose` elements and the expanded values shall be stored in the `.expansion` element. Developers shall use the `.expansion` element for populating UI elements.

Tasks:
- [x] Identify ValueSet(s) that need expansion (or modification to fit business needs)
- [x] Create expanded ValueSet (manually or with an external tool)
- [x] Upload Expanded ValueSet (create a new branch called `bugfix/valueset/<RESOURCE>`)

**Comment by Gokulsignal** [comment]
Hi @enjoysparkling , the valuesets for the Patient profile have been added, kindly review and let me know any changes requried. 

Note: 
This attributes doesnt required valueset addition.

**Patient.extension:adoptionInfo.value[x]**
