### ISSUE TITLE
Create Custom Search Parameter for reason reference in Communications resource

### ISSUE THREAD

**Issue by arunsundar-m** [enjoysparkling/signal-mso-fhir-profiles#123]
Create custom search parameter reason-reference to store the document reference in Communications resource

@enjoysparkling @Gokulsignal

Attaching the script to create in Forge, @enjoysparkling - do you know how $reindex can be applied for Search Parameter as part of package deployment.

API developer had done this manually in Dev and I did this in QA.

https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-run-a-reindex

**Comment by arunsundar-m** [comment]
[Add Custom Search Variable in HL7.txt](https://github.com/enjoysparkling/signal-mso-fhir-profiles/files/13166208/Add.Custom.Search.Variable.in.HL7.txt)

**Comment by enjoysparkling** [comment]
> @enjoysparkling - do you know how $reindex can be applied for Search Parameter as part of package deployment.
> 
> API developer had done this manually in Dev and I did this in QA.
> 
> https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-run-a-reindex

Since this is Azure FHIR Service -specific, this will have to be run *after* the package is loaded.  We should probably have a script for "Post-Package Load" runs in case there is anything else like this.

**Comment by Gokulsignal** [comment]
@enjoysparkling Search Parameter for the Communication-ReasonReference is created and committed. 
Kindly review.

**Comment by enjoysparkling** [comment]
Would someone share where they found this or how they went about generating it?  I see the url is listed as `http://hl7.org/fhir/SearchParameter/Communication-reason-reference`, but I cannot find it on hl7.org (e.g. it is not listed as a [communication extension](http://hl7.org/fhir/extensions/extensions-Communication.html).)  If we created it custom, the URL shall represent signalbhn.org

**Comment by arunsundar-m** [comment]
This is a custom search parameter that we created for Devs to use Document Reference. 

@Gokulsignal Can you please change this URL to signalbhn.org and check with API team if they are fine with this change to understand there won't be any impact for them

**Comment by Gokulsignal** [comment]
URL is updated on the Custom search parameter.  It is updated to the API team about this change.  
Below is the updated one.
https://signalbhn.org/fhir/SearchParameter/Communication-reason-reference

**Comment by enjoysparkling** [comment]
Background info:
As an implementer (dev), I need to be able to use the `Communication.reasonReference` element as a search parameter find the DocumentReference resource that is linked off the communication.  

Tasks / Additional info / Approach :
* using [Azure's how-to guide](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-do-custom-search), creating a custom search parameter for this field
* Also need to follow instructions to [reindex](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-run-a-reindex) the field, after the new search parameter resource is loaded

Future note:  
* reindex needs to be done manually on the FHIR Service after the FHIR package is loaded (who does this?)
