### ISSUE TITLE
Update Organization.qualification value set for Service type

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#129]
As an implementer I need to be able to assign both the License and the Service Type to the qualification.code element.

---

Tasks:
- [ ] add SignalServiceType to the qualification.code ValueSet.  Should contain both licenses and services.

**Comment by arunsundar-m** [comment]
@enjoysparkling Do we need to create a new valueset named valueset-signal-service-type pulling the values from the two custom code systems codesystem-healthcare-service-type and codesystem-organization-license? then binding the new valueset to qualification.code?

**Comment by arunsundar-m** [comment]
The business is thinking of having these combined. If the business changes its mind to keep them together, we can revisit this issue.

**Comment by enjoysparkling** [comment]
If we need to do this in the future, I would like to combine the Code systems for license (https://simplifier.net/signal-mso-fhir-profiles/signal-organization-license) and service types (https://simplifier.net/signal-mso-fhir-profiles/signal-healthcare-service-type-duplicate-2) into the license valueset: https://signalbhn.org/fhir/ValueSet/signal-organization-license
