### ISSUE TITLE
ValueSet bugfix for Organization

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#14]
As a business user, I want to be able to be able to access all my value sets (seed tables) from my FHIR server.
- Azure FHIR service [does not have terminology services](https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/fhir-faq#does-azure-api-for-fhir-support-any-terminology-operations--) (see https://github.com/microsoft/fhir-server/issues/897, https://github.com/microsoft/fhir-server/issues/810), so we will need to host all [ValueSets as extensional](http://hl7.org/fhir/valueset.html#int-ext) files.
- We prefer developers utilize the canonical URL for [identifying a ValueSet](http://hl7.org/fhir/valueset.html#ident). So, any value set that does not have extended values from FHIR will need to be hosted from our package.  _Note:_ We should be able to keep the same canonical URL, as long as our package loads last, thereby loading and overriding the original package ValueSet with our expanded version.
- A [ValueSet expansion](https://www.hl7.org/fhir/valueset.html#expansion) shall keep the originally defined `.compose` elements and the expanded values shall be stored in the `.expansion` element. Developers shall use the `.expansion` element for populating UI elements.

Tasks:
- [x] Identify ValueSet(s) that need expansion (or modification to fit business needs)
- [x] Create expanded ValueSet (manually or with an external tool)
- [x] Upload Expanded ValueSet (create a new branch called `bugfix/valueset/<RESOURCE>`)
- [x] ~~Create Profile binding for expanded ValueSet (only necessary on a modified ValueSet)~~
- [x] ~~Update documentation for modified value sets~~
   - (move guides/Signal-Implementation-Guide/Index/assets/images into the Business-Context folder)
- [x] Update documentation for standard value sets
- [x] Delete [StructureDefinition-profile-organization.json](https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/main/input/resources/StructureDefinition-profile-organization.json), now using [StructureDefinition-profile-SignalUSCoreOrganizationProfile](https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/main/input/resources/StructureDefinition-profile-SignalUSCoreOrganizationProfile.json)

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, I have updated the expansion attribute for Organization profile related valuesets. Kindly review and let me know if any changes are required

**Comment by enjoysparkling** [comment]
@arunsundar-m - check the latest commits for the documentation updates I did.  I need you to add to the **Terminology** table.  See the address-type example I made.  Do this for each of the Organization, OrganizationAffiliation, and HealthcareService value sets.

We will need to do this for every Resource Type, so if you want to go ahead, get those going.  I don't yet have every page for the *Structure Definition*, but you can just leave the link off of it and add every other resource.

I am using this Implementation Guide (IG) as the example:  https://simplifier.net/guide/ca-on-ereferral-r4-iguide-v0.11.0/Index/terminology2/terminology?version=0.11.0

**Comment by enjoysparkling** [comment]
Merged.
