### ISSUE TITLE
Bugfix for ServiceRequest category, other diffs

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#144]
A few things that need investigation and potential correction RE https://simplifier.net/signal-mso-fhir-profiles/signalservicerequest:
- ServiceRequest.category:serviceCategory - I think this needs to be bound to [Service Category VS](https://simplifier.net/signal-mso-fhir-profiles/signal-healthcare-service-category-duplicate-2)
- We should ALSO have a ServiceRequest.category:serviceType slice that is bound to the [Service Type VS](https://simplifier.net/signal-mso-fhir-profiles/signal-healthcare-service-type-duplicate-2)
- Why do elements `.status` and `.intent` have differential from the base resource?  There aren't any changes here, are there?

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/c0474f5f-34b4-4999-ac9e-054aeab3f319)

**Comment by arunsundar-m** [comment]
@enjoysparkling @Gokulsignal 

- ServiceRequest.category:serviceCategory - I think this needs to be bound to [Service Category VS](https://simplifier.net/signal-mso-fhir-profiles/signal-healthcare-service-category-duplicate-2) - This is already taken care of another issue #132 

- We should ALSO have a ServiceRequest.category:serviceType slice that is bound to the [Service Type VS] - Added as part of the new commit(https://simplifier.net/signal-mso-fhir-profiles/signal-healthcare-service-type-duplicate-2)

- Why do elements .status and .intent have differential from the base resource? There aren't any changes here, are there? By default, valueset reference URLs are http://hl7.org/fhir/ValueSet/request-status|4.0.1 and http://hl7.org/fhir/ValueSet/request-intent|4.0.1, we have just trimmed "|4.0.1" at the end.

**Comment by enjoysparkling** [comment]
> * Why do elements .status and .intent have differential from the base resource? There aren't any changes here, are there? By default, valueset reference URLs are [http://hl7.org/fhir/ValueSet/request-status|4.0.1](http://hl7.org/fhir/ValueSet/request-status%7C4.0.1) and [http://hl7.org/fhir/ValueSet/request-intent|4.0.1](http://hl7.org/fhir/ValueSet/request-intent%7C4.0.1), we have just trimmed "|4.0.1" at the end.

I must have been asleep when I accepted those.  We _should not_ change the baseDefinition.  Why were those changed?  Those pipes and version numbers should not cause any issues.
