### ISSUE TITLE
Extension race missing from Patient resource

### ISSUE THREAD

**Issue by arunsundar-m** [enjoysparkling/signal-mso-fhir-profiles#145]
While adding identifier for Julota in patient, the extension race was added. When I checked the main branch, it was not found. So created this issue to include race extension.

@enjoysparkling @Gokulsignal

**Comment by enjoysparkling** [comment]
I don't understand.  The race extension was from the US Core base resource.  Would you describe what you are seeing and what you think is wrong?

**Comment by arunsundar-m** [comment]
While I was working on the Patient identifier slice for Julota issue, race extension appeared as a change. Thought this was missing from the package. If we are good, I can mark the ticket as closed.

**Comment by enjoysparkling** [comment]
Remove the differentials on ethnicity and tribalAffiliation that were introduced in #69 in Patient:

https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/a319376bd3a5afc0ead610b31ab87588eccc552a/input/resources/StructureDefinition-profile-SignalPatient.json#L19

```
      {
        "id": "Patient.extension:ethnicity",
        "path": "Patient.extension",
        "sliceName": "ethnicity"
      },
      {
        "id": "Patient.extension:ethnicity.extension",
        "path": "Patient.extension.extension",
        "min": 1
      },
      {
        "id": "Patient.extension:tribalAffiliation",
        "path": "Patient.extension",
        "sliceName": "tribalAffiliation"
      },
      {
        "id": "Patient.extension:tribalAffiliation.extension",
        "path": "Patient.extension.extension",
        "min": 1
      },
```
