### ISSUE TITLE
Add IG Terminology documentation for standard HL7 value sets

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#41]
As am implementor, I want to understand the references for all my value sets (seed tables) that are used in the implementation guide.

- [ ] Update implementation guide terminology page with links to each value set

---

I need you to add to the Terminology table. See the address-type example I made here: https://simplifier.net/guide/Signal-Implementation-Guide/Index/Terminology?version=current. Do this for each of the Organization, OrganizationAffiliation, and HealthcareService value sets.

I need you to do this for every Resource Type. I don't yet have every page for the Structure Definition, but you can just leave the link off of it and add every other value set to that table. Split the work with Gokul as you see fit.

I am using this Implementation Guide (IG) as the example: https://simplifier.net/guide/ca-on-ereferral-r4-iguide-v0.11.0/Index/terminology2/terminology?version=0.11.0

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, I have updated the valuesets to IG terminology table and committed the changes. Kindly review.
