### ISSUE TITLE
Add Organization.qualification to R4 resource for ASAM

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#5]
Story: As an implementer, I want the ability to capture Organization-level licenses on the US Core profile. It does not exist in FHIR R4 (US Core 6). It does exist in R5, so we want to match closely with that.  

Tasks:
- [x] Find or create a comparable extension
- [x] Add Organization.qualification extension (see below)
- [ ] Create the associated value sets needed for model

----- 

Extension:
1. Read through the proposed extention:
    - Note: [FHIR R5 Core Organization.qualification](https://hl7.org/fhir/R5/organization-definitions.html#Organization.qualification) now exists, but we are using R4 and need to find another solution for it.  
    - ~~[HL7.FHIR.US.NDH\NDH Qualification - FHIR v4.0.1](https://build.fhir.org/ig/HL7/fhir-us-ndh/StructureDefinition-base-ext-qualification.html)~~
    - [HL7.FHIR.US.DAVINCI-PDEX-PLAN-NET\Qualification](https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/StructureDefinition-qualification.html)
3. Add that extension to our existing [Organization](https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/main/input/resources/StructureDefinition-profile-organization.json)
4. Create the pull request

Regarding the ASAM level:  
I believe it belongs in the [Organization](https://www.hl7.org/fhir/organization.html) resource in the qualification element

**Comment by KasiSribal** [comment]
Added file to feature/Organization/qualification. Please review

**Comment by enjoysparkling** [comment]
As I try to add the extension to Organization, I am getting an error in Forge because I do not have the HL7.FHIR.US.NDH dependency.  I am unable to find the project on Simplifier, so I have a question out to Firely on how best to incorporate either the extension or dependency package:

> Description
> I am interested in using the Organization.qualification extension.  Although it is available in FHIR R5 Core on Organization, I am using the US Core Organization as my basis, which uses FHIR R4.  So, I need a creative way to add qualification to my Organization profile.
> I found an equivalent R4 extension in the [HL7.FHIR.US.NDH\Home - FHIR v4.0.1](https://build.fhir.org/ig/HL7/fhir-us-ndh/) implementation guide.  However, I do not see that project on Simplifier.  
> Two-fold question:
> - Is this an acceptable (best??) way to add .qualification to organization?  Or would there be a better way to pull it from the FHIR R5 spec down into R4?
> - How do I specify the package dependencies in Forge or Simplifier, since the project does not exist on the Simplifier platform? That is, If I do end up using [HL7.FHIR.US.NDH\Home - FHIR v4.0.1](https://build.fhir.org/ig/HL7/fhir-us-ndh/). I can only find the Package on [build.fhir.org](http://build.fhir.org/):  [HL7.FHIR.US.NDH\Download Specification - FHIR v4.0.1](https://build.fhir.org/ig/HL7/fhir-us-ndh/downloads.html)

**Comment by enjoysparkling** [comment]
Also wanted to note: Those ASAM files do not look like ones we can use.  I am going to revert those commits.  They are close but are not going to cut it.  I am working on defining them further.  See internal docs on that. I will give next steps.

**Comment by enjoysparkling** [comment]
This will be addressed in #11.
