### ISSUE TITLE
HealthcareService binding changes, category, services

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#79]
Changes to HealthcareService:
- `.type.serviceCategory` should be removed.  This binding should be done to the `.category` element
- .type should have a slice called 'services' that uses the [valueset-service-type.json](https://simplifier.net/resolve?scope=hl7.fhir.r4.core@4.0.1&filepath=package/ValueSet-service-type.json].  This slice should contain and require .service and .procedure, both rolling up to the .category.
-

**Comment by arunsundar-m** [comment]
@enjoysparkling I have updated the changes required and made the commits, please verify.
