### ISSUE TITLE
Patient address.district missing binding to counties value set

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#8]
As an implementer, I would like the Patient.address.district bound to the applicable Colorado counties.  We already have the [county valueset](https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/main/input/vocabulary/valueset-address-fips-county-colorado.json) created, we just need to link it.

**Comment by enjoysparkling** [comment]
@KasiSribal or @Gokulsignal, would one of you add the binding as "Required" to the Patient profile?

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, I have updated the patient profile json, could you please check if thats updated correctly?

**Comment by enjoysparkling** [comment]
@arunsundar-m - when you're ready for a review, feel free to create the Pull Request.  I went ahead and did it this time.
