### ISSUE TITLE
Region specification - potential Address.extension

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#9]
As a user, I would like the ability to select and search a Signal business-specific region for Organization locations.  E.g. South, North, SouthWest, etc.

~~@Gokulsignal - Can we confirm - is this needed on the UI?~~

This will likely need to be covered by an [Address datatype extension](https://hl7.org/fhir//r4/datatypes-extras.html#address).  I am unable to find anything we can reuse , so we may have to build this from scratch.  
I believe this will be a business-specific, reusable value set ~~(is there a code system we can base this on??)~~.  It needs to represent the business's definitions of region.  

This will be applicable to ~~Organization and potentially to Location, Patient, and other resources that directly reference a location~~ Location only at this point.

---

Tasks:

- [ ] Create extension to .address
- [ ] Create code system
- [ ] Create value set
- [ ] Apply extension to Location.address

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, We have discussed with UI team and created a story in JIRA to get their consent. It looks like this field is not used anywhere in the UI.

We can close this issue.

cc @Gokulsignal

Thanks,
Arun

**Comment by enjoysparkling** [comment]
If it is needed in the future or for some non-UI classification reasons, we can re-open this issue.

**Comment by enjoysparkling** [comment]
This is back in play.  It will be referenced from the OrganizationAffiliation, since it will represent in what Business region a provider-location operates in relation to the service organization.

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, Please review the changes I have made for adding region, I have not created a pull request as there might be naming changes.

#https://github.com/enjoysparkling/signal-mso-fhir-profiles/commit/80128756e6731ffa0c7508e84ff35cea68e08ab1
